apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sysdig-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SimiOps/argocd-applications
    targetRevision: main
    path: sysdig-agent
    helm:
      chart: shield
      repoURL: https://charts.sysdig.com
      version: "1.23.2"
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sysdig-agent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
